//! Gherkin → bats generator (ADR-002's bats facts).
//!
//! One `@test "<scenario name>"` per scenario, calling `step_<slug>` shell
//! functions. Scenario Outlines expand into one test per Examples row,
//! suffixed ` [row N]` (bats has no parameterization); the bats verify
//! adapter strips the suffix and aggregates rows back into one scenario
//! result.
//!
//! Step lookup is layered at run time: the write-once `steps.bash.template`
//! (every function a `skip "step not implemented: …"` stub — the skip
//! message ADR-002 maps to Undefined) is sourced first, then the human's
//! `steps.bash` — so implemented steps override their stubs one by one and
//! everything else honestly reports Undefined.

use std::fmt::Write as _;

use super::{StepRegistry, typed_params};

/// The marker prefix generated stubs pass to `skip`; the `JUnit` `Bats`
/// dialect maps a skip carrying it to `Undefined` (ADR-002; defined once in
/// the normalizer).
pub use crate::verify::normalize::NOT_IMPLEMENTED_PREFIX;

/// The ` [row N]` suffix marking an expanded outline row.
pub const ROW_SUFFIX_MARKER: &str = " [row ";

/// Generator output: the regenerated runner file and the write-once step
/// stub template.
#[derive(Debug)]
pub struct GeneratedBash {
    pub runner: String,
    pub steps_template: String,
}

/// Generate the `.bats` runner and step stub template for a linted feature.
///
/// # Errors
/// [`super::GenError::MixedExampleHeaders`] when an outline's Examples
/// tables disagree on headers.
pub fn generate(feature: &gherkin::Feature) -> Result<GeneratedBash, super::GenError> {
    let mut registry = StepRegistry::default();
    let mut tests = String::new();

    let scenarios = feature
        .scenarios
        .iter()
        .chain(feature.rules.iter().flat_map(|r| r.scenarios.iter()));
    for scenario in scenarios {
        match super::example_table(scenario)? {
            None => {
                let calls: Vec<super::StepCall> = scenario
                    .steps
                    .iter()
                    .map(|s| registry.call(&s.keyword, &s.value, &[]))
                    .collect();
                write_test(&mut tests, &scenario.name, &calls, &[]);
            }
            Some(table) => {
                let headers = typed_params(&table);
                let calls: Vec<super::StepCall> = scenario
                    .steps
                    .iter()
                    .map(|s| registry.call(&s.keyword, &s.value, &headers))
                    .collect();
                for (i, row) in table.rows.iter().enumerate() {
                    let name = format!("{}{}{}]", scenario.name, ROW_SUFFIX_MARKER, i + 1);
                    let args: Vec<(&str, &str)> = table
                        .headers
                        .iter()
                        .zip(row)
                        .map(|(h, v)| (h.as_str(), v.as_str()))
                        .collect();
                    write_test(&mut tests, &name, &calls, &args);
                }
            }
        }
    }

    let mut runner = String::from(HEADER);
    runner.push_str(tests.trim_end_matches('\n'));
    runner.push('\n');
    Ok(GeneratedBash {
        runner,
        steps_template: steps_template(&registry),
    })
}

const HEADER: &str = "\
#!/usr/bin/env bats
# GENERATED by craftsman spec gen — do not edit.
# Fully regenerated from SPEC.md on every run (this file is the CLI's, per
# the single-writer rule). Step implementations live in your own steps.bash
# next to this file — craftsman never touches it. The stub template is
# sourced first, so any step you have not (re)defined skips as
# \"step not implemented\" and craftsman verify reports it as Undefined.

setup() {
    source \"$BATS_TEST_DIRNAME/steps.bash.template\"
    if [ -f \"$BATS_TEST_DIRNAME/steps.bash\" ]; then
        source \"$BATS_TEST_DIRNAME/steps.bash\"
    fi
}

";

/// One `@test` block: the (possibly row-suffixed) name and the step calls
/// with the row's values substituted for outline placeholders.
fn write_test(out: &mut String, name: &str, calls: &[super::StepCall], row: &[(&str, &str)]) {
    let _ = writeln!(out, "@test \"{}\" {{", bash_string(name));
    if calls.is_empty() {
        out.push_str("    : # SPEC.md lists no steps for this scenario.\n");
    }
    for call in calls {
        let mut args = String::new();
        for p in &call.params {
            let value = row
                .iter()
                .find(|(h, _)| *h == p.header)
                .map_or("", |(_, v)| *v);
            let _ = write!(args, " \"{}\"", bash_string(value));
        }
        let _ = writeln!(out, "    {}{args}", call.name);
    }
    out.push_str("}\n\n");
}

fn steps_template(registry: &StepRegistry) -> String {
    let mut out = String::from(
        "\
#!/usr/bin/env bash
# Step implementations for SPEC.md — written ONCE by `craftsman spec gen`
# and never overwritten (this file is yours from now on). Implement steps by
# redefining these functions in steps.bash next to this file: the generated
# runner sources this template first, then steps.bash, so your definitions
# win one function at a time. Positional arguments are the Scenario Outline
# values, in placeholder order. A function left as a stub skips with the
# \"step not implemented:\" marker, which craftsman verify reports as
# Undefined rather than Failed.

",
    );
    for f in registry.fns() {
        let _ = write!(
            out,
            "# {}\n{}() {{\n    skip \"{NOT_IMPLEMENTED_PREFIX}{}\"\n}}\n\n",
            f.display,
            f.name,
            bash_string(&f.display),
        );
    }
    out.trim_end_matches('\n').to_owned() + "\n"
}

/// Escape for a bash double-quoted string: `\`, `"`, `$`, and backtick.
fn bash_string(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        if matches!(c, '\\' | '"' | '$' | '`') {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn feature() -> gherkin::Feature {
        let text = "\
Feature: Todo management

  Scenario: Adding a todo shows it in the list
    Given an empty todo list
    When I add a todo \"Buy milk\"
    Then the list contains \"Buy milk\"

  Scenario Outline: Rejecting an invalid quantity
    Given a cart with quantity 1
    When I set the quantity to <quantity>
    Then the update is rejected as \"<reason>\"

    Examples:
      | quantity | reason   |
      | 0        | zero     |
      | -3       | negative |
";
        gherkin::Feature::parse(text, gherkin::GherkinEnv::default()).expect("fixture parses")
    }

    #[test]
    fn runner_expands_scenarios_and_outline_rows() {
        let out = generate(&feature()).expect("generates");
        let r = &out.runner;
        assert!(r.starts_with("#!/usr/bin/env bats\n# GENERATED"), "{r}");
        assert!(
            r.contains("@test \"Adding a todo shows it in the list\" {"),
            "{r}"
        );
        assert!(
            r.contains("@test \"Rejecting an invalid quantity [row 1]\" {"),
            "{r}"
        );
        assert!(
            r.contains("@test \"Rejecting an invalid quantity [row 2]\" {"),
            "{r}"
        );
        assert!(r.contains("    step_i_set_the_quantity_to \"0\""), "{r}");
        assert!(r.contains("    step_i_set_the_quantity_to \"-3\""), "{r}");
        assert!(r.contains("steps.bash.template"), "{r}");
        // The quoted literal in the step text stays inside the slug.
        assert!(r.contains("    step_i_add_a_todo_buy_milk"), "{r}");
    }

    #[test]
    fn steps_template_stubs_every_unique_step_with_skip() {
        let out = generate(&feature()).expect("generates");
        let t = &out.steps_template;
        assert!(
            t.contains(
                "step_an_empty_todo_list() {\n    \
                 skip \"step not implemented: Given an empty todo list\"\n}"
            ),
            "{t}"
        );
        // Placeholder step: message keeps the placeholder text.
        assert!(
            t.contains("skip \"step not implemented: When I set the quantity to <quantity>\""),
            "{t}"
        );
        assert_eq!(t.matches("skip \"step not implemented: ").count(), 6, "{t}");
    }

    #[test]
    fn bash_strings_escape_expansion_hazards() {
        assert_eq!(
            bash_string(r#"a "b" $c `d` \e"#),
            r#"a \"b\" \$c \`d\` \\e"#
        );
    }
}
