//! bats adapter (bash stack), driving the `.bats` file generated by
//! `craftsman spec gen` (ADR-002's bats facts).
//!
//! Invocation: `bats --formatter junit <bats-dir>` — the `JUnit` XML arrives
//! on STDOUT (ADR-002), so it is captured, not redirected to a file. bats
//! exits 1 on failure with the XML still written, and a `-f` filter
//! matching nothing exits 0 printing a `1..0`-shaped empty suite — so
//! craftsman counts testcases itself; zero results become the dispatcher's
//! exit 4.
//!
//! Selection: one anchored ERE per run,
//! `^(<escaped-name>|…)( \[row [0-9]+\])?$` — the optional suffix keeps
//! expanded Scenario Outline rows (the generator's ` [row N]` convention)
//! selected together with their scenario.
//!
//! Ingestion: `JUnit` via [`JunitDialect::Bats`] (skip message
//! `step not implemented` → Undefined), then outline rows are aggregated
//! back into one result per scenario (worst status wins, durations sum).

use std::path::Path;
use std::process::{Command, Stdio};

use super::{AdapterError, tail};
use crate::codegen::bash::ROW_SUFFIX_MARKER;
use crate::verify::normalize::{JunitDialect, ScenarioResult, parse_junit};

/// Run bats on the generated spec file and normalize its `JUnit` stdout.
///
/// # Errors
/// [`AdapterError`] on spawn failure, a failing runner without parseable
/// XML, or unparseable XML on a green exit.
pub fn run(
    bats_dir: &Path,
    scenario_names: Option<&[String]>,
) -> Result<Vec<ScenarioResult>, AdapterError> {
    let mut cmd = Command::new("bats");
    cmd.arg("--formatter").arg("junit").arg(bats_dir);
    if let Some(names) = scenario_names {
        cmd.arg("-f").arg(names_pattern(names));
    }
    let command_line = "bats --formatter junit".to_owned();

    let output = cmd
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .output()
        .map_err(|source| AdapterError::Spawn {
            command: command_line.clone(),
            dir: bats_dir.to_path_buf(),
            source,
        })?;

    // The XML on stdout is the sole verdict source (module docs).
    let stdout = String::from_utf8_lossy(&output.stdout);
    match parse_junit(&stdout, JunitDialect::Bats) {
        Ok(results) => Ok(aggregate_rows(results)),
        Err(err) => {
            if output.status.success() {
                return Err(err.into());
            }
            Err(AdapterError::RunnerFailed {
                command: command_line,
                code: output
                    .status
                    .code()
                    .map_or_else(|| "signal".to_owned(), |c| c.to_string()),
                output_tail: tail(&stdout, 20),
            })
        }
    }
}

/// Anchored ERE alternation of escaped names, each optionally carrying the
/// generator's outline-row suffix.
fn names_pattern(names: &[String]) -> String {
    let escaped: Vec<String> = names.iter().map(|n| super::regex_escape(n)).collect();
    format!("^({})( \\[row [0-9]+\\])?$", escaped.join("|"))
}

/// Fold expanded outline rows (` [row N]` names) back into one result per
/// scenario: worst status wins, durations sum, first failure detail is
/// kept (prefixed with its row).
fn aggregate_rows(results: Vec<ScenarioResult>) -> Vec<ScenarioResult> {
    let mut out: Vec<ScenarioResult> = Vec::new();
    for mut r in results {
        let (name, row) = split_row_suffix(&r.scenario);
        let Some(row) = row else {
            out.push(r);
            continue;
        };
        r.scenario = name;
        if let Some(existing) = out.iter_mut().find(|e| e.scenario == r.scenario) {
            if r.status > existing.status {
                existing.status = r.status;
                if let Some(f) = r.failure.as_deref() {
                    existing.failure = Some(format!("[{row}] {f}"));
                }
            }
            existing.duration_ms = match (existing.duration_ms, r.duration_ms) {
                (Some(a), Some(b)) => Some(a + b),
                (a, b) => a.or(b),
            };
        } else {
            r.failure = r.failure.take().map(|f| format!("[{row}] {f}"));
            out.push(r);
        }
    }
    out
}

/// `"Name [row 3]"` → `("Name", Some("row 3"))`; anything else passes
/// through with `None`.
fn split_row_suffix(scenario: &str) -> (String, Option<String>) {
    if let Some(stripped) = scenario.strip_suffix(']')
        && let Some(pos) = stripped.rfind(ROW_SUFFIX_MARKER)
    {
        let row = &stripped[pos + ROW_SUFFIX_MARKER.len()..];
        if !row.is_empty() && row.bytes().all(|b| b.is_ascii_digit()) {
            return (scenario[..pos].to_owned(), Some(format!("row {row}")));
        }
    }
    (scenario.to_owned(), None)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::verify::normalize::Status;

    #[test]
    fn names_pattern_allows_outline_row_suffixes() {
        let names = vec!["Plain name".to_owned(), "Costs $4.99".to_owned()];
        assert_eq!(
            names_pattern(&names),
            r"^(Plain name|Costs \$4\.99)( \[row [0-9]+\])?$"
        );
    }

    #[test]
    fn split_row_suffix_only_matches_the_generator_convention() {
        assert_eq!(
            split_row_suffix("Name [row 12]"),
            ("Name".to_owned(), Some("row 12".to_owned()))
        );
        assert_eq!(
            split_row_suffix("Name [row twelve]"),
            ("Name [row twelve]".to_owned(), None)
        );
        assert_eq!(split_row_suffix("Plain"), ("Plain".to_owned(), None));
    }

    #[test]
    fn aggregate_rows_folds_worst_status_and_sums_durations() {
        let row = |n: usize, status: Status, ms: u64, failure: Option<&str>| ScenarioResult {
            feature: "f".to_owned(),
            scenario: format!("Outline [row {n}]"),
            status,
            duration_ms: Some(ms),
            failure: failure.map(str::to_owned),
        };
        let agg = aggregate_rows(vec![
            row(1, Status::Passed, 5, None),
            row(2, Status::Failed, 7, Some("boom")),
            row(3, Status::Undefined, 1, Some("step not implemented: x")),
            ScenarioResult {
                feature: "f".to_owned(),
                scenario: "Plain".to_owned(),
                status: Status::Passed,
                duration_ms: Some(2),
                failure: None,
            },
        ]);
        assert_eq!(agg.len(), 2);
        assert_eq!(agg[0].scenario, "Outline");
        assert_eq!(agg[0].status, Status::Failed);
        assert_eq!(agg[0].duration_ms, Some(13));
        assert_eq!(agg[0].failure.as_deref(), Some("[row 2] boom"));
        assert_eq!(agg[1].scenario, "Plain");
    }
}
