//! Swift Testing adapter (swift stack), driving the code generated by
//! `craftsman spec gen` (ADR-001).
//!
//! `SwiftPM` invocation:
//! `swift test --experimental-event-stream-output <artifacts>/swift-ev.jsonl
//! --experimental-event-stream-version 0 --xunit-output <artifacts>/swift-xunit.xml`
//! in the package directory. The version flag is pinned to `0` and the
//! `version` field inside the records is the contract (ADR-001: the flag
//! itself is not validated by the toolchain).
//!
//! Selection: one `--filter` per requested scenario using the ADR-001
//! unique-selection recipe ``Target\.Suite/`<escaped name>`\(`` — never
//! `$`-anchored (the test ID continues with the source location). A filter
//! matching nothing exits 0 with an empty run, so craftsman counts matched
//! tests itself; zero results become the dispatcher's exit 4.
//!
//! Ingestion: the JSONL event stream is primary (per-Examples-row results
//! exist only there); the `*-swift-testing.xml` xunit sibling is a coarse
//! fallback when the stream is missing or unreadable.
//!
//! xcodebuild variant (`[verify.swift] scheme`): handled by the sibling
//! `xcodebuild` adapter (Batch 9a) — the verify dispatcher routes on the
//! presence of `scheme`, so this adapter only ever sees the `SwiftPM` path.

use std::path::Path;
use std::process::{Command, Stdio};

use super::{AdapterError, tail};
use crate::verify::normalize::{
    JunitDialect, ScenarioResult, parse_junit, parse_swift_events_jsonl,
};

/// Run `swift test` on the package and normalize its event stream.
///
/// `test_target` and `suite` are the generated test-target and `@Suite`
/// struct names (`codegen::swift` rebuilds both deterministically) — the
/// anchors of the ADR-001 filter recipe.
///
/// # Errors
/// [`AdapterError`] on spawn failure, a failing runner that produced no
/// artifacts, or artifacts neither parser can read.
pub fn run(
    package_dir: &Path,
    artifacts_dir: &Path,
    test_target: &str,
    suite: &str,
    scenario_names: Option<&[String]>,
) -> Result<Vec<ScenarioResult>, AdapterError> {
    std::fs::create_dir_all(artifacts_dir).map_err(|source| AdapterError::ResultsPath {
        path: artifacts_dir.to_path_buf(),
        source,
    })?;
    let jsonl_path = artifacts_dir.join("swift-ev.jsonl");
    let xunit_path = artifacts_dir.join("swift-xunit.xml");
    // The real xunit lands in the `-swift-testing.xml` sibling (ADR-001).
    let xunit_sibling = artifacts_dir.join("swift-xunit-swift-testing.xml");
    for path in [&jsonl_path, &xunit_path, &xunit_sibling] {
        if path.exists() {
            std::fs::remove_file(path).map_err(|source| AdapterError::ResultsPath {
                path: path.clone(),
                source,
            })?;
        }
    }

    let mut cmd = Command::new("swift");
    cmd.arg("test")
        .arg("--experimental-event-stream-output")
        .arg(&jsonl_path)
        .arg("--experimental-event-stream-version")
        .arg("0")
        .arg("--xunit-output")
        .arg(&xunit_path);
    if let Some(names) = scenario_names {
        for name in names {
            cmd.arg("--filter")
                .arg(filter_recipe(test_target, suite, name));
        }
    }
    let command_line = "swift test".to_owned();

    let output = cmd
        .current_dir(package_dir)
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .output()
        .map_err(|source| AdapterError::Spawn {
            command: command_line.clone(),
            dir: package_dir.to_path_buf(),
            source,
        })?;
    // Runner stdout is progress, not verdict: forward it to stderr.
    eprint!("{}", String::from_utf8_lossy(&output.stdout));

    // JSONL primary; xunit sibling as coarse fallback (module docs).
    if jsonl_path.is_file() {
        let text =
            std::fs::read_to_string(&jsonl_path).map_err(|source| AdapterError::ReadResults {
                path: jsonl_path.clone(),
                source,
            })?;
        match parse_swift_events_jsonl(&text) {
            Ok(results) => return Ok(results),
            Err(err) => {
                eprintln!(
                    "swift test: event stream unreadable ({err}) — falling back \
                     to the xunit sibling (coarse: no per-row results)"
                );
            }
        }
    }
    if xunit_sibling.is_file() {
        let text = std::fs::read_to_string(&xunit_sibling).map_err(|source| {
            AdapterError::ReadResults {
                path: xunit_sibling.clone(),
                source,
            }
        })?;
        return Ok(parse_junit(&text, JunitDialect::SwiftTesting)?);
    }

    if output.status.success() {
        return Err(AdapterError::NoResults {
            path: jsonl_path,
            hint: "swift test ran green but wrote no event stream — does the \
                   toolchain support --experimental-event-stream-output \
                   (Swift 6+)?"
                .to_owned(),
        });
    }
    // Most likely a compile error (already streamed to stderr).
    let stdout = String::from_utf8_lossy(&output.stdout);
    Err(AdapterError::RunnerFailed {
        command: command_line,
        code: output
            .status
            .code()
            .map_or_else(|| "signal".to_owned(), |c| c.to_string()),
        output_tail: tail(&stdout, 20),
    })
}

/// The ADR-001 unique-selection filter:
/// ``Target\.Suite/`<escaped name>`\(`` — matched unanchored against
/// the full test ID, which continues with `/File.swift:line:col`, so it
/// must NEVER be `$`-anchored after the parenthesis.
fn filter_recipe(test_target: &str, suite: &str, name: &str) -> String {
    format!(
        "{}\\.{}/`{}`\\(",
        super::regex_escape(test_target),
        super::regex_escape(suite),
        super::regex_escape(name)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn filter_recipe_matches_the_adr_shape() {
        assert_eq!(
            filter_recipe(
                "SpecSpikeTests",
                "TodoManagementFeature",
                "Adding a todo shows it in the list"
            ),
            r"SpecSpikeTests\.TodoManagementFeature/`Adding a todo shows it in the list`\("
        );
        // Metacharacters in the name are escaped; no trailing anchor ever.
        let f = filter_recipe("T", "S", "Costs $4.99 (really)?");
        assert_eq!(f, r"T\.S/`Costs \$4\.99 \(really\)\?`\(");
        assert!(!f.ends_with('$'));
    }
}
