//! `craftsman adr` — the strategic ledger's hygiene tools (ledgers
//! research).
//!
//! `adr index` regenerates the <500-token `decisions/index.md` entry
//! point; `adr stale` is projectmem's stale-memory detection applied to
//! ADRs — compare each active ADR's last commit against later commits
//! touching the files it cites, and advise "confirm or supersede".
//! Staleness is advice, never a gate: findings exit 0.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde::Serialize;
use thiserror::Error;

use crate::config::{Config, ConfigError};
use crate::ledger::LedgerError;

/// Errors of the adr commands. Exit 3 territory (staleness findings are
/// not errors).
#[derive(Debug, Error)]
pub enum AdrError {
    #[error(transparent)]
    Config(#[from] ConfigError),
    #[error("no ADR directory at {path} — set [adr] dir in craftsman.toml")]
    NoDir { path: PathBuf },
    #[error("cannot read or write {path}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    /// A failing git query (the ledger module's shared plumbing).
    #[error(transparent)]
    Git(#[from] LedgerError),
}

/// One ADR's front section.
#[derive(Debug, Serialize)]
pub struct Decision {
    /// File name (e.g. `ADR-004-batch-6b-gate-decisions.md`).
    pub file: String,
    /// First `#` heading, verbatim.
    pub title: String,
    /// First token of the `Status:` line (`accepted`, `superseded`, …);
    /// `unknown` when absent.
    pub status: String,
}

/// What `adr index` wrote.
#[derive(Debug, Serialize)]
pub struct IndexReport {
    pub path: String,
    pub decisions: Vec<Decision>,
    /// chars/4 estimate of the generated index.
    pub token_estimate: usize,
    /// Set when the estimate exceeds the 500-token budget.
    pub over_budget: bool,
}

/// One staleness advisory.
#[derive(Debug, Serialize)]
pub struct StaleFinding {
    pub file: String,
    pub status: String,
    /// Commits that touched cited files after the ADR's last commit.
    pub commits_since: u64,
    pub threshold: u64,
    pub cited: Vec<String>,
    pub advice: String,
}

/// The ADR files in the configured directory (default `decisions/`),
/// sorted, excluding the generated `index.md`.
fn adr_files(dir: &Path) -> Result<Vec<PathBuf>, AdrError> {
    if !dir.is_dir() {
        return Err(AdrError::NoDir {
            path: dir.to_path_buf(),
        });
    }
    let entries = std::fs::read_dir(dir).map_err(|source| AdrError::Io {
        path: dir.to_path_buf(),
        source,
    })?;
    let mut files: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| {
            p.is_file()
                && p.extension().is_some_and(|e| e == "md")
                && p.file_name().is_some_and(|n| n != "index.md")
        })
        .collect();
    files.sort();
    Ok(files)
}

/// Parse one ADR's title and status from its front section.
fn parse_front(path: &Path) -> Result<Decision, AdrError> {
    let text = std::fs::read_to_string(path).map_err(|source| AdrError::Io {
        path: path.to_path_buf(),
        source,
    })?;
    let title = text
        .lines()
        .find_map(|l| l.strip_prefix("# "))
        .unwrap_or("(untitled)")
        .trim()
        .to_owned();
    // Accept `Status: accepted · …` and the bold `**Status: X** — …` form
    // (both live in this repo's decisions/).
    let status = text
        .lines()
        .find_map(|l| {
            l.trim()
                .trim_start_matches('*')
                .trim_start()
                .strip_prefix("Status:")
        })
        .map_or_else(
            || "unknown".to_owned(),
            |rest| {
                rest.split(['·', ',', ';', '—'])
                    .next()
                    .unwrap_or_default()
                    .trim_matches(|c: char| c == '*' || c.is_whitespace())
                    .to_owned()
            },
        );
    Ok(Decision {
        file: path
            .file_name()
            .map_or_else(String::new, |n| n.to_string_lossy().into_owned()),
        title,
        status,
    })
}

/// Regenerate `decisions/index.md`: one line per decision.
///
/// # Errors
/// [`AdrError`] on a missing directory or filesystem failure.
pub fn index(root: &Path, config: &Config) -> Result<IndexReport, AdrError> {
    let dir = root.join(config.adr.dir());
    let mut decisions = Vec::new();
    for file in adr_files(&dir)? {
        decisions.push(parse_front(&file)?);
    }

    let mut text = String::from(
        "# Decisions index\n\n\
         <!-- GENERATED by `craftsman adr index` — regenerate, don't edit. -->\n\n",
    );
    for d in &decisions {
        let _ = writeln!(text, "- [{}]({}) — {}", d.title, d.file, d.status);
    }
    let token_estimate = text.chars().count() / 4;
    let over_budget = token_estimate > 500;

    let path = dir.join("index.md");
    std::fs::write(&path, &text).map_err(|source| AdrError::Io {
        path: path.clone(),
        source,
    })?;
    Ok(IndexReport {
        path: path
            .strip_prefix(root)
            .unwrap_or(&path)
            .to_string_lossy()
            .into_owned(),
        decisions,
        token_estimate,
        over_budget,
    })
}

/// Path-shaped tokens in an ADR that exist in the repo: candidate tokens
/// keep `[A-Za-z0-9_./-]`, must contain `/`, and must name an existing
/// file or directory under `root`.
#[must_use]
pub fn cited_paths(root: &Path, text: &str) -> Vec<String> {
    let mut cited = Vec::new();
    for raw in text.split(|c: char| !(c.is_ascii_alphanumeric() || "_./-".contains(c))) {
        let token = raw.trim_matches(|c: char| c == '.' || c == '/' || c == '-');
        if !token.contains('/') || token.len() < 3 {
            continue;
        }
        if root.join(token).exists() && !cited.contains(&token.to_owned()) {
            cited.push(token.to_owned());
        }
    }
    cited
}

/// Cross-reference active ADRs against the git history of the files they
/// cite. Report-only: the caller prints findings and exits 0.
///
/// # Errors
/// [`AdrError`] when git fails (exit 3) — advice built on a broken query
/// would be false confidence.
pub fn stale(root: &Path, config: &Config) -> Result<Vec<StaleFinding>, AdrError> {
    let dir = root.join(config.adr.dir());
    let threshold = config.adr.stale_commits();
    let mut findings = Vec::new();
    for file in adr_files(&dir)? {
        let decision = parse_front(&file)?;
        if decision.status.eq_ignore_ascii_case("superseded")
            || decision.status.eq_ignore_ascii_case("rejected")
        {
            continue;
        }
        let text = std::fs::read_to_string(&file).map_err(|source| AdrError::Io {
            path: file.clone(),
            source,
        })?;
        let cited = cited_paths(root, &text);
        if cited.is_empty() {
            continue;
        }
        let rel = file.strip_prefix(root).unwrap_or(&file).to_path_buf();
        let Some(adr_commit) = last_commit(root, &rel)? else {
            continue; // uncommitted ADR: no history to compare yet
        };
        let commits_since = commits_touching_since(root, &adr_commit, &cited)?;
        if commits_since > threshold {
            findings.push(StaleFinding {
                file: rel.to_string_lossy().into_owned(),
                status: decision.status.clone(),
                commits_since,
                threshold,
                advice: format!(
                    "{} predates {commits_since} commit(s) to files it cites \
                     — confirm or supersede",
                    decision.title
                ),
                cited,
            });
        }
    }
    Ok(findings)
}

/// The last commit touching `path`, or `None` for uncommitted files.
fn last_commit(root: &Path, path: &Path) -> Result<Option<String>, AdrError> {
    let out = crate::ledger::git(
        root,
        &["log", "-n1", "--format=%H", "--", &path.to_string_lossy()],
    )?;
    let sha = String::from_utf8_lossy(&out).trim().to_owned();
    Ok((!sha.is_empty()).then_some(sha))
}

/// Commits after `since` that touched any of `paths`.
fn commits_touching_since(root: &Path, since: &str, paths: &[String]) -> Result<u64, AdrError> {
    let range = format!("{since}..HEAD");
    let mut args: Vec<&str> = vec!["rev-list", "--count", &range, "--"];
    for p in paths {
        args.push(p);
    }
    let out = crate::ledger::git(root, &args)?;
    Ok(String::from_utf8_lossy(&out).trim().parse().unwrap_or(0))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config() -> Config {
        Config::from_toml(
            "[project]\nname = \"demo\"\nstacks = [\"rust\"]\n",
            Path::new("craftsman.toml"),
        )
        .expect("minimal config")
    }

    #[test]
    fn index_lists_one_line_per_decision_with_status() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let dir = tmp.path().join("decisions");
        std::fs::create_dir_all(&dir).expect("mkdirs");
        std::fs::write(
            dir.join("ADR-001-alpha.md"),
            "# ADR-001: Alpha choice\n\nStatus: accepted · Date: 2026-07-17\n\nBody.\n",
        )
        .expect("write");
        std::fs::write(
            dir.join("ADR-002-beta.md"),
            "# ADR-002: Beta choice\n\nStatus: superseded by ADR-003\n",
        )
        .expect("write");
        let report = index(tmp.path(), &config()).expect("index");
        assert_eq!(report.decisions.len(), 2);
        assert!(!report.over_budget);
        let text = std::fs::read_to_string(dir.join("index.md")).expect("read index");
        assert!(
            text.contains("- [ADR-001: Alpha choice](ADR-001-alpha.md) — accepted"),
            "{text}"
        );
        assert!(
            text.contains("- [ADR-002: Beta choice](ADR-002-beta.md) — superseded"),
            "{text}"
        );
        assert!(text.contains("GENERATED"), "{text}");
    }

    #[test]
    fn bold_status_lines_parse_too() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let dir = tmp.path().join("decisions");
        std::fs::create_dir_all(&dir).expect("mkdirs");
        std::fs::write(
            dir.join("ADR-001-a.md"),
            "# ADR-001: A\n\n**Status: Proven-with-constraints** — every claim tested.\n",
        )
        .expect("write");
        let report = index(tmp.path(), &config()).expect("index");
        assert_eq!(report.decisions[0].status, "Proven-with-constraints");
    }

    #[test]
    fn index_regeneration_excludes_itself() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let dir = tmp.path().join("decisions");
        std::fs::create_dir_all(&dir).expect("mkdirs");
        std::fs::write(
            dir.join("ADR-001-a.md"),
            "# ADR-001: A\n\nStatus: accepted\n",
        )
        .expect("write");
        index(tmp.path(), &config()).expect("first");
        let report = index(tmp.path(), &config()).expect("second");
        assert_eq!(report.decisions.len(), 1, "index.md itself is excluded");
    }

    #[test]
    fn missing_dir_is_a_loud_error() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let err = index(tmp.path(), &config()).expect_err("no decisions dir");
        assert!(matches!(err, AdrError::NoDir { .. }), "{err}");
    }

    #[test]
    fn cited_paths_keep_only_existing_repo_paths() {
        let tmp = tempfile::tempdir().expect("tempdir");
        std::fs::create_dir_all(tmp.path().join("src/verify")).expect("mkdirs");
        std::fs::write(tmp.path().join("src/verify/mod.rs"), "").expect("write");
        let text = "See `src/verify/mod.rs` and src/verify — but not \
                    ghost/path.rs, nor bare words, nor a/b.";
        let cited = cited_paths(tmp.path(), text);
        assert_eq!(
            cited,
            vec!["src/verify/mod.rs".to_owned(), "src/verify".to_owned()]
        );
    }
}
